default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: likelater_dev

test:
  <<: *default
  database: likelater_test

production:
  <<: *default
  database: likelater
