default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  password: <%= ENV['LIKELATER_DB_PASSWORD'] %>
  username: <%= ENV['LIKELATER_DB_USER'] %>

development:
  <<: *default
  database: likelater_dev
  host: 127.0.0.1
  port: 5433

test:
  <<: *default
  database: likelater_test

production:
  <<: *default
  database: likelater
